language: python
python:
  - "3.6"

install:
    - sudo apt-get install ninja-build
    - pip install .
    - python setup.py build
    - python setup.py build_ext --inplace

script:
    - pytest

deploy:
    skip_cleanup: true

