language: python
python:
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# Build steps taken from
# https://github.com/nanomsg/nanomsg#build-it-with-cmake
before_install:
    - sudo apt-get install ninja-build

install:
    - pip install -e .
    - python setup.py build && python setup.py bdist_wheel sdist && python setup.py develop
    - ls pynng

before_script:
    - pip install pytest

script:
    - ls pynng
    - pytest test

deploy:
    skip_cleanup: true

