language: python
python:
  - "3.6"

install:
    - sudo apt-get install ninja-build
    - pip install -e .
    - python setup.py build build_ext sdist

script:
    - pytest

deploy:
    skip_cleanup: true

